### ISSUE TITLE
Design hover element

### ISSUE THREAD

**Issue by michaelsena** [3box/profile-hover#1]
- [ ] design UI element
- [ ] design hover element

**Comment by zachferland** [comment]
Plan is to have two optional design params, short/full address and sytled/or not. The one now is the shortened and styled one. But want to also offer full address, and option that is just plain text address with hover, no style, dev can add their own styling if wanted, just to truly make it possible to add to any app. 

Some remaining questions:

For shortened address, where can we put the full address or copy button?
How do we want to show addresses with no profile? will there be a call to action in the hover?
I think we can concern ourselves with mobile view after ethdenver, but we can see what it looks like
Feedback/thoughts on v1?

**Comment by zachferland** [comment]
Also what data do we want in the hover? right now is name/emoji, then twitter, github, website, image, do we want other data? or attempts at different fallbacks if a profile doesn't have github or twitter for example

**Comment by zachferland** [comment]
Actually think it good solution is just put a copy icon to right of bar, easier than showing the entire address anywhere and more clear than placing anywhere redundantly inside the hover.
