### ISSUE TITLE
Implement UI for react hover component

### ISSUE THREAD

**Issue by michaelsena** [3box/profile-hover#20]

**Comment by oznekenzo** [comment]
- [x] 2 images
- [x] prof image
- [x] no image
- [x] empty hover state
- [x] when profile img or cover img is the only field a user has but is turned off 
- [x] click on name to go to profile
- [x] add description, no label
- [x] default for background image, white or light grey

**Comment by oznekenzo** [comment]
- [x] logo links to 3box profile
- [x] no address on hover if empty profile
- [x] add address to hover component
- [x] click to copy in profile hover
- [x] remove click to copy on dtw
- [x] click button to hover on mobile
- [x] use link in component if provided
- [x] provide link to component
- [x] style base tile
- [x] click to copy links on web3 mobile
- [x] prevent zoom on mobile click to copy
- [x] show copy confirmation
