### ISSUE TITLE
Refactor and Document CSS to enable custom themes

### ISSUE THREAD

**Issue by michaelsena** [3box/profile-hover#28]
Refactor code, and document how to make custom theme in readme

**Comment by oznekenzo** [comment]
@michaelsena let's add an option for font as well

**Comment by michaelsena** [comment]
@oznekenzo sure I added it to the section above, as long as it's not a lot of work

**Comment by zachferland** [comment]
I personally would not add so many options, while some of it should be customizable, there is also a lot of value in having a well recognized piece of 3box spread through the web, with some parts more influenced by our choices. If someone really wants something so unique, they will build it them selfs, that isn't so much of a stretch still. We are not going to be able to cover all options in all environments, and wouldn't want to have to support that (or at least not yet)

Also advanced users can override css classes if they want.

Also configs are only easier to pass to react component, the general component would be a bit of mess to pass so many configs. Would need something like a config builder to create the piece of code in a friendly way. 

This all depends on how many other options for data/etc you are thinking about as well. But just some added context, up to you guys.

**Comment by oznekenzo** [comment]
@michaelsena what did we decide for this? If someone wanted to change the background color, say, it's pretty easy to do that manually, as Zach mentioned.
