### ISSUE TITLE
Write documentation in readme

### ISSUE THREAD

**Issue by michaelsena** [3box/profile-hover#29]
This should include an overview and how to use the profile-hover component

Includes options for:
- custom themes
- size
- name
- orientation
- images
- etc

**Comment by michaelsena** [comment]
We should probably update the GIF that's in the readme documentation to reflect the new design! :) @oznekenzo

**Comment by oznekenzo** [comment]
True!
I’ll do that.

**Comment by michaelsena** [comment]
Also @oznekenzo, there used to be a URL where we had examples of these components. Does that still exist? If so can we add it to the readme? cc @zachferland

**Comment by zachferland** [comment]
its in the repo short description - https://3box.github.io/profile-hover/example/ and react would be https://3box.github.io/profile-hover/example/react but will have to add some files for that to work
